# Generated by Django 5.2.1 on 2025-05-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_student_course_remove_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('Enrolled', 'Enrolled'), ('Completed', 'Completed')], default='Enrolled', max_length=20),
        ),
    ]
