-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.auth_group
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_group_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.auth_group_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.auth_permission
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename)
);

CREATE TABLE IF NOT EXISTS public.contact_contact
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    subject character varying(200) COLLATE pg_catalog."default" NOT NULL,
    message text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL,
    is_read boolean NOT NULL,
    CONSTRAINT contact_contact_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.courses_certificate
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    issued_at timestamp with time zone NOT NULL,
    certificate_file character varying(100) COLLATE pg_catalog."default" NOT NULL,
    enrollment_id bigint NOT NULL,
    CONSTRAINT courses_certificate_pkey PRIMARY KEY (id),
    CONSTRAINT courses_certificate_enrollment_id_key UNIQUE (enrollment_id)
);

CREATE TABLE IF NOT EXISTS public.courses_course
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    title character varying(200) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    duration integer NOT NULL,
    price numeric(10, 2) NOT NULL,
    "courseImage" character varying(100) COLLATE pg_catalog."default",
    "courseType" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    what_you_will_learn text COLLATE pg_catalog."default" NOT NULL,
    slug character varying(200) COLLATE pg_catalog."default",
    instructor_id bigint NOT NULL,
    category character varying(20) COLLATE pg_catalog."default",
    level character varying(20) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL,
    requirements text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT courses_course_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.courses_coursevideo
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    lesson_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    video_url character varying(200) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    duration integer NOT NULL,
    "order" integer NOT NULL,
    course_id bigint,
    CONSTRAINT courses_coursevideo_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.courses_enrollment
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    date date NOT NULL,
    course_id bigint NOT NULL,
    student_id bigint NOT NULL,
    progress double precision NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT courses_enrollment_pkey PRIMARY KEY (id),
    CONSTRAINT courses_enrollment_student_id_course_id_2d19b567_uniq UNIQUE (student_id, course_id)
);

CREATE TABLE IF NOT EXISTS public.courses_instructor
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    profile_pic character varying(100) COLLATE pg_catalog."default",
    bio text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone,
    expertise character varying(200) COLLATE pg_catalog."default",
    is_instructor boolean NOT NULL,
    phone_number character varying(20) COLLATE pg_catalog."default" NOT NULL,
    updated_at timestamp with time zone,
    user_id bigint,
    CONSTRAINT courses_instructor_pkey PRIMARY KEY (id),
    CONSTRAINT courses_instructor_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.courses_payment
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    date date NOT NULL,
    price numeric(10, 2) NOT NULL,
    enrollment_id bigint NOT NULL,
    currency character varying(3) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT courses_payment_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.courses_review
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    date date NOT NULL,
    rating integer NOT NULL,
    comment text COLLATE pg_catalog."default" NOT NULL,
    course_id bigint NOT NULL,
    student_id bigint NOT NULL,
    CONSTRAINT courses_review_pkey PRIMARY KEY (id),
    CONSTRAINT courses_review_student_id_course_id_59eddf9e_uniq UNIQUE (student_id, course_id)
);

CREATE TABLE IF NOT EXISTS public.courses_student
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    phone character varying(15) COLLATE pg_catalog."default" NOT NULL,
    profile_pic character varying(100) COLLATE pg_catalog."default",
    user_id bigint,
    CONSTRAINT courses_student_pkey PRIMARY KEY (id),
    CONSTRAINT courses_student_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.courses_transaction
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    amount numeric(10, 2) NOT NULL,
    date date NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    course_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT courses_transaction_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.courses_videocompletion
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    completed_at timestamp with time zone NOT NULL,
    enrollment_id bigint NOT NULL,
    video_id bigint NOT NULL,
    CONSTRAINT courses_videocompletion_pkey PRIMARY KEY (id),
    CONSTRAINT courses_videocompletion_enrollment_id_video_id_4e24cfe9_uniq UNIQUE (enrollment_id, video_id)
);

CREATE TABLE IF NOT EXISTS public.django_admin_log
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    action_time timestamp with time zone NOT NULL,
    object_id text COLLATE pg_catalog."default",
    object_repr character varying(200) COLLATE pg_catalog."default" NOT NULL,
    action_flag smallint NOT NULL,
    change_message text COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_content_type
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    app_label character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id),
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model)
);

CREATE TABLE IF NOT EXISTS public.django_migrations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    app character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    applied timestamp with time zone NOT NULL,
    CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_session
(
    session_key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    session_data text COLLATE pg_catalog."default" NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);

CREATE TABLE IF NOT EXISTS public.token_blacklist_blacklistedtoken
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL,
    CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id),
    CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id)
);

CREATE TABLE IF NOT EXISTS public.token_blacklist_outstandingtoken
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    token text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id bigint,
    jti character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id),
    CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti)
);

CREATE TABLE IF NOT EXISTS public.users_user
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    last_login timestamp with time zone,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    is_student boolean NOT NULL,
    is_instructor boolean NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    is_superuser boolean NOT NULL,
    profile_picture character varying(100) COLLATE pg_catalog."default",
    date_joined timestamp with time zone NOT NULL,
    phone character varying(15) COLLATE pg_catalog."default",
    role character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT users_customuser_pkey PRIMARY KEY (id),
    CONSTRAINT users_customuser_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.users_user_groups
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id bigint NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT users_customuser_groups_pkey PRIMARY KEY (id),
    CONSTRAINT users_customuser_groups_customuser_id_group_id_76b619e3_uniq UNIQUE (user_id, group_id)
);

CREATE TABLE IF NOT EXISTS public.users_user_user_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id bigint NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT users_customuser_user_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT users_customuser_user_pe_customuser_id_permission_7a7debf6_uniq UNIQUE (user_id, permission_id)
);

ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_84c5c92e
    ON public.auth_group_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_b120cbf9
    ON public.auth_group_permissions(group_id);


ALTER TABLE IF EXISTS public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_2f476e4b
    ON public.auth_permission(content_type_id);


ALTER TABLE IF EXISTS public.courses_certificate
    ADD CONSTRAINT courses_certificate_enrollment_id_b4d6cdb3_fk_courses_e FOREIGN KEY (enrollment_id)
    REFERENCES public.courses_enrollment (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS courses_certificate_enrollment_id_key
    ON public.courses_certificate(enrollment_id);


ALTER TABLE IF EXISTS public.courses_coursevideo
    ADD CONSTRAINT courses_coursevideo_course_id_8b812ed7_fk_courses_course_id FOREIGN KEY (course_id)
    REFERENCES public.courses_course (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS courses_coursevideo_course_id_8b812ed7
    ON public.courses_coursevideo(course_id);


ALTER TABLE IF EXISTS public.courses_enrollment
    ADD CONSTRAINT courses_enrollment_course_id_2631503e_fk_courses_course_id FOREIGN KEY (course_id)
    REFERENCES public.courses_course (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS courses_enrollment_course_id_2631503e
    ON public.courses_enrollment(course_id);


ALTER TABLE IF EXISTS public.courses_enrollment
    ADD CONSTRAINT courses_enrollment_student_id_aebf8536_fk_courses_student_id FOREIGN KEY (student_id)
    REFERENCES public.courses_student (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS courses_enrollment_student_id_aebf8536
    ON public.courses_enrollment(student_id);


ALTER TABLE IF EXISTS public.courses_instructor
    ADD CONSTRAINT courses_instructor_user_id_7ec37e0f_fk_users_user_id FOREIGN KEY (user_id)
    REFERENCES public.users_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS courses_instructor_user_id_key
    ON public.courses_instructor(user_id);


ALTER TABLE IF EXISTS public.courses_payment
    ADD CONSTRAINT courses_payment_enrollment_id_a4d02d64_fk_courses_enrollment_id FOREIGN KEY (enrollment_id)
    REFERENCES public.courses_enrollment (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS courses_payment_enrollment_id_a4d02d64
    ON public.courses_payment(enrollment_id);


ALTER TABLE IF EXISTS public.courses_review
    ADD CONSTRAINT courses_review_course_id_536a14f9_fk_courses_course_id FOREIGN KEY (course_id)
    REFERENCES public.courses_course (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS courses_review_course_id_536a14f9
    ON public.courses_review(course_id);


ALTER TABLE IF EXISTS public.courses_review
    ADD CONSTRAINT courses_review_student_id_8ff1cb1a_fk_courses_student_id FOREIGN KEY (student_id)
    REFERENCES public.courses_student (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS courses_review_student_id_8ff1cb1a
    ON public.courses_review(student_id);


ALTER TABLE IF EXISTS public.courses_transaction
    ADD CONSTRAINT courses_transaction_course_id_a684bda2_fk_courses_course_id FOREIGN KEY (course_id)
    REFERENCES public.courses_course (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS courses_transaction_course_id_a684bda2
    ON public.courses_transaction(course_id);


ALTER TABLE IF EXISTS public.courses_transaction
    ADD CONSTRAINT courses_transaction_user_id_de60bb97_fk_users_user_id FOREIGN KEY (user_id)
    REFERENCES public.users_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS courses_transaction_user_id_de60bb97
    ON public.courses_transaction(user_id);


ALTER TABLE IF EXISTS public.courses_videocompletion
    ADD CONSTRAINT courses_videocomplet_enrollment_id_9ea916d2_fk_courses_e FOREIGN KEY (enrollment_id)
    REFERENCES public.courses_enrollment (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS courses_videocompletion_enrollment_id_9ea916d2
    ON public.courses_videocompletion(enrollment_id);


ALTER TABLE IF EXISTS public.courses_videocompletion
    ADD CONSTRAINT courses_videocomplet_video_id_82da0919_fk_courses_c FOREIGN KEY (video_id)
    REFERENCES public.courses_coursevideo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS courses_videocompletion_video_id_82da0919
    ON public.courses_videocompletion(video_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_c4bce8eb
    ON public.django_admin_log(content_type_id);


ALTER TABLE IF EXISTS public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id)
    REFERENCES public.token_blacklist_outstandingtoken (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS token_blacklist_blacklistedtoken_token_id_key
    ON public.token_blacklist_blacklistedtoken(token_id);


ALTER TABLE IF EXISTS public.users_user_groups
    ADD CONSTRAINT users_customuser_groups_group_id_01390b14_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS users_customuser_groups_group_id_01390b14
    ON public.users_user_groups(group_id);


ALTER TABLE IF EXISTS public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_5f6f5a90_fk_users_user_id FOREIGN KEY (user_id)
    REFERENCES public.users_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS users_customuser_groups_customuser_id_958147bf
    ON public.users_user_groups(user_id);


ALTER TABLE IF EXISTS public.users_user_user_permissions
    ADD CONSTRAINT users_customuser_use_permission_id_baaa2f74_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS users_customuser_user_permissions_permission_id_baaa2f74
    ON public.users_user_user_permissions(permission_id);


ALTER TABLE IF EXISTS public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_20aca447_fk_users_user_id FOREIGN KEY (user_id)
    REFERENCES public.users_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS users_customuser_user_permissions_customuser_id_5771478b
    ON public.users_user_user_permissions(user_id);

END;